using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace questionnaire
{
    internal class Axiom_TriangleFactorOver500
    {

        //https://stackoverflow.com/questions/17541364/find-the-first-triangular-number-which-has-50-factors
        //C#
        //Highly divisible triangular number
        //The sequence of triangle numbers is generated by adding the natural numbers.What is the value of the first triangle number to have over five hundred divisors?

        //Solution?
        //In the Solution box please type the source code of your sol

        //        Example
        //The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
        //1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
        //Let us list the divisors of the first seven triangle numbers:
        //1: 1
        //3: 1,3
        //6: 1,2,3,6
        //10: 1,2,5,10
        //15: 1,3,5,15
        //21: 1,3,7,21
        //28: 1,2,4,7,14,28
        //What is the value of the first triangle number to have over five divisors?
        //The output is "28".

        /// <summary>
        /// Listing all numbers comes under Triangular series.
        /// </summary>
        /// <param name="number"></param>
        /// <returns></returns>
        public static List<int> GetTriangularNumbers(int number)
        {
            List<int> lstTriangularNumbers = new List<int>();
            int i;
            int sum = 0;
            int triangularNumber = 0;
            for (i = 1; i < number; i++)
            {
                sum = sum + i;
                triangularNumber = sum;
                lstTriangularNumbers.Add(triangularNumber);
            }
            return lstTriangularNumbers;
        }

        /// <summary>
        /// returns(count) the number of factors for each number
        /// </summary>
        /// <param name="number"></param>
        /// <returns></returns>
        public static int FactorCount(int number)
        {
            List<int> factors = new List<int>();
            int max = (int)Math.Sqrt(number);  //round down
            for (int factor = 1; factor <= max; ++factor)
            {
                //test from 1 to the square root, or the int below it, inclusive.
                if (number % factor == 0)
                {
                    factors.Add(factor);
                    if (factor != number / factor)
                    {
                        // Don't add the square root twice!  
                        factors.Add(number / factor);
                    }
                }
            }
            return factors.Count;
        }

        static void AxionMain(string[] args)
        {
            List<int> lstTriangularNumbers = new List<int>();
            List<int> factors = new List<int>();
            int count = 0;
            //Getting the list of numbers comes under triangular series till 5000
            lstTriangularNumbers = GetTriangularNumbers(50000);

            foreach (int number in lstTriangularNumbers)
            {
                /*
                 * Calling the FactorCount(number) function to check no of factors 
                 * available for the specific triangular number - number.
                 */
                count = FactorCount(number);
                //Console.WriteLine("No of factors for : " + number + " is : " + count);
                if (count >= 500)
                {
                    //Console.WriteLine("No of factors for first Triangular Number : " + number + " is : " + count);
                    Console.WriteLine(number);
                    break;
                }

            }
            Console.ReadLine();
        }

    }
}
